import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://staging.gotsurge.co/login');
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').fill('chintya.qlip@gmail.com');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('gotsurgeq@');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByRole('button', { name: 'Fill Form' }).click();
  await page.getByRole('button', { name: 'Marine Delivery & offland' }).click();
  await page.getByText('Enter manually').click();
  await page.getByPlaceholder('BEAGLE').click();
  await page.getByPlaceholder('BEAGLE').fill('Automation 2');
  await page.getByPlaceholder('1234567').click();
  await page.getByPlaceholder('1234567').fill('1234567');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByPlaceholder('Jan, 10:00 AM').click();
  await page.getByLabel('Next Month').click();
  await page.getByLabel('Choose Monday, September 9th,').click();
  await page.getByRole('option', { name: '5:00 PM' }).click();
  await page.getByPlaceholder('Jan, 11:30 AM').click();
  await page.getByLabel('Next Month').click();
  await page.getByLabel('Choose Wednesday, September 18th,').click();
  await page.getByRole('option', { name: '11:30 PM' }).click();
  await page.getByRole('button', { name: 'Land' }).nth(2).click();
  await page.getByPlaceholder('Jurong West Street 88').click();
  await page.locator('div:nth-child(2) > .sc-kCMKrZ > .sc-deXhhX').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Enter contact details...' }).click();
  await page.getByPlaceholder('Company Name').click();
  await page.getByPlaceholder('Company Name').fill('Chocolate');
  await page.getByPlaceholder('Seas the Day / GBX 1234 T').click();
  await page.getByPlaceholder('Seas the Day / GBX 1234 T').fill('Cho-cho');
  await page.getByPlaceholder('Eg: Amy Amin').click();
  await page.getByPlaceholder('Eg: Amy Amin').fill('Silver Q');
  await page.getByPlaceholder('8989').click();
  await page.getByPlaceholder('8989').fill('+6578954514');
  await page.getByRole('button', { name: 'Confirm' }).click({timeout:30000});
  await page.locator('form div').filter({ hasText: 'Fill in Pickup & Delivery DetailsA.Collect FromType of location *LandSeaPickup' }).getByRole('textbox').first().click();
  await page.getByLabel('Choose Wednesday, August 14th,').click();
  await page.getByRole('option', { name: '17:00' }).click();
  await page.getByPlaceholder('E.g. Meet at the loading bay').first().click();
  await page.getByPlaceholder('E.g. Meet at the loading bay').first().fill('QA Tester - T01');
  await page.getByRole('button', { name: 'Land' }).nth(3).click();
  await page.getByPlaceholder('Jurong West Street 88').click();
  await page.locator('div:nth-child(2) > .sc-kCMKrZ > .sc-deXhhX > .sc-imwsjW').click();
  await page.getByPlaceholder('#01-').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.locator('div:nth-child(3) > .sc-etVdmn > .sc-etlCFv > .sc-gEkIjz').click();
  await page.getByPlaceholder('Company Name').click();
  await page.getByPlaceholder('Company Name').fill('Baloon');
  await page.getByPlaceholder('Seas the Day / GBX 1234 T').click();
  await page.getByPlaceholder('Seas the Day / GBX 1234 T').fill('Green Baloon');
  await page.getByPlaceholder('Eg: Amy Amin').click();
  await page.getByPlaceholder('Eg: Amy Amin').fill('Dooor');
  await page.getByPlaceholder('8989').fill('78945121');
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Select a vehicle...' }).click();
  await page.getByRole('button', { name: '24ft Truck 750 × 230 × 230 cm' }).click();
  await page.getByRole('button', { name: 'Select Cargo' }).click();
  await page.locator('div').filter({ hasText: /^Cold Bin$/ }).click();
  await page.waitForTimeout(2000)
  await page.getByRole('button', { name: 'Place Order' }).click();
  await page.locator('div:nth-child(2) > .sc-hIUJlX > .sc-jnOGJG').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
});